---
title: "rcourseday7"
author: "Nicolas Reigl"
date: "3/9/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(stringr)
```

Help for left join
```{r}
?left_join

```

```{r}
taxdata <- read_csv("http://www.ut.ee//~iseppo/taxdata.gz")
```

```{r}
names(taxdata)
```

```{r}
nr_of_companys <-taxdata %>% 
  group_by(quarter, county) %>% 
  summarise(nrOfCompanies = n())
```

or 


```{r}
nr_of_companys <-taxdata %>% 
  group_by(quarter, county) %>% 
  summarise(nrOfCompanies = length(unique(code))) #  unique creates vector so we need also length
```



```{r}
nr_of_companys
```

```{r}
spread(nr_of_companys, key = "quarter", value = "nrOfCompanies")
```

Who has county of NA?

```{r}
uhuu <- taxdata %>% 
  filter(is.na(county))

```


An overly quick intro to regression in R

```{r}
piaac<-read.csv("http://www.ut.ee/~iseppo/piaacest.csv")
```


```{r}
piaac
```



```{r}
piaac$logincome<- log(piaac$earnmth)
```

```{r}
str(piaac)
summary(piaac)
```


```{r}
ggplot(piaac, 
       aes(x=pvnum1, y=logincome))+
  geom_point()+
  geom_smooth(aes(color = gender))
```


```{r}
model1<- lm(logincome ~ edlevel3 + gender, weights = weights, data = piaac)
```



```{r}
summary(model1)
```

```{r}
model2<- lm(logincome ~ edlevel3 + gender +poly(age,2), weights = weights, data = piaac)

```

```{r}
summary(model2)
```

```{r}
str(model1)
```


```{r}
model1[["coefficients"]]["edlevel3Low"]
```


Broom

```{r}
library(broom)
```

```{r}
model1overview <- tidy(model1)
```



```{r}
model1overview
```



```{r}
glance(model1)
```


```{r}
piaacRes <- augment(model1, piaac)
```



```{r}
ggplot(piaacRes, aes(x=age, y=.resid))+
  geom_point()+
  geom_smooth()+
  theme_minimal()
```


```{r}
predict(model1, newdata = data.frame(gender ="Male", edlevel3="Low", age = 30))
```

```{r}
mydata <-expand.grid(edlevel3 = unique((piaac$edlevel3)), gender = levels(piaac$gender), age = c(10:100))
```

```{r}
possiblevalues <- augment(model1, newdata = mydata)
```


```{r}
possiblevalues
```

```{r}
library(forecast)
piaac$edlevel3 <- fct_relevel(piaac$edlevel3, "Medium")
```


```{r}
ggplot(possiblevalues, aes(x=age, y=.fitted))+
  geom_line()


```


```{r}
library(sjPlot)
```


```{r}
sjp.lm(model1)
```


```{r}
# library(brms)
# fit<-brm(logincome ~ edlevel3 + gender +poly(age,2), data = piaac)
```

```{r}
# summary(fit)
```


```{r}
library(stargazer)
stargazer(model1)

```


# Simulation study

```{r}
simdata <- data.frame(gender=c(rep("Male", 600), rep("Female", 1400)))
```

```{r}
simdata
```


```{r}
rbinom(n =1, size=1, prob = 0.5)
```


```{r}
rbinom(n=10, size = 1, prob = 0.5)
```


```{r}
rbinom(n=10, size = 1, prob = 0.5)
```



```{r}
set.seed(1)
rbinom(n=10, size = 1, prob = 0.5)

```


```{r}
simdata$height <- NA
```


```{r}
simdata$height[simdata$gender=="Male"]<-rnorm(n = 600, mean = 180, sd = 8)
```

```{r}
simdata$height[simdata$gender=="Female"]<-rnorm(n =1400, mean = 173, sd = 8)
```



You turn 

```{r}
ggplot(simdata, aes(x=height))+
  geom_histogram()+
  geom_vline(aes(xintercept=mean(height, na.rm=T)),   # Ignore NA values for mean
               color="red", linetype="dashed", size=1) +
  facet_wrap(~gender)
```

